# Graded Questions

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
df = pd.read_csv('Training_Set.csv')
df

    Attribute 1 (a1)  Attribute 2 (a2)  Class Label
0                  2                11            2
1                  2                13            2
2                  2                15            2
3                  2                27            1
4                  2                39            1
5                  4                11            1
6                  4                13            1
7                  4                15            1
8                  4                27            2
9                  4                39            2
10                 6                11            1
11                 6                13            1
12                 6                15            1
13                 6                27            2
14                 6                39            2
15                 8                11            1
16                 8                13            1
17                 8                15            1
18                 8                27            2
19                 8                39            2
20                10                11            1
21                10                13            1
22                10                15            1
23                10                27            2
24                10                39            2
25                12                11            2
26                12                13            1
27                12                15            2
28                12                27            2
29                12                39            2