## Investment Analysis Assignment

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
%matplotlib inline

In [3]:
companies = pd.read_csv('companies.csv',encoding= 'unicode_escape')

In [4]:
rounds2 = pd.read_csv("rounds2.csv", encoding= 'unicode_escape')

In [5]:
print(companies.columns,companies.shape)

Index(['permalink', 'name', 'homepage_url', 'category_list', 'status',
       'country_code', 'state_code', 'region', 'city', 'founded_at'],
      dtype='object') (66368, 10)

In [6]:
companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66368 entries, 0 to 66367
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   permalink      66368 non-null  object
 1   name           66367 non-null  object
 2   homepage_url   61310 non-null  object
 3   category_list  63220 non-null  object
 4   status         66368 non-null  object
 5   country_code   59410 non-null  object
 6   state_code     57821 non-null  object
 7   region         58338 non-null  object
 8   city           58340 non-null  object
 9   founded_at     51147 non-null  object
dtypes: object(10)
memory usage: 5.1+ MB

In [7]:
companies.describe()

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
count,66368,66367,61310,63220,66368,59410,57821,58338,58340,51147
unique,66368,66099,61191,27296,4,137,311,1092,5111,3978
top,/Organization/Teebeedee,Blink,http://www.askforoffer.com,Software,operating,USA,CA,SF Bay Area,San Francisco,01-01-2012
freq,1,4,5,3995,53034,37601,12900,8804,3526,2730

In [8]:
companies['permalink']= companies['permalink'].apply(lambda x:str(x).lower())

### Unique companies Count  in Companies CSV

In [9]:
print(companies['name'].nunique())

66099

In [10]:
companies.shape

(66368, 10)

In [11]:
companies['permalink'].nunique()

66368

In [12]:
companies.head(12)

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/organization/-fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
5,/organization/01games-technology,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
6,/organization/0ndine-biomedical-inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
7,/organization/0xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
8,/organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
9,/organization/1-2-3-listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012
10,/organization/1-4-all,1-4 All,NaN,Entertainment|Games|Software,operating,USA,NC,NC - Other,Connellys Springs,NaN
11,/organization/1-618-technology,1.618 Technology,http://www.Homeandcondogallery.com,Networking|Real Estate|Web Hosting,operating,USA,FL,Orlando,Orlando,07-12-2013

In [13]:
print(rounds2.columns,rounds2.shape)

Index(['company_permalink', 'funding_round_permalink', 'funding_round_type',
       'funding_round_code', 'funded_at', 'raised_amount_usd'],
      dtype='object') (114949, 6)

### Unique companies count in rounds2 csv

In [14]:
rounds2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114949 entries, 0 to 114948
Data columns (total 6 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   company_permalink        114949 non-null  object
 1   funding_round_permalink  114949 non-null  object
 2   funding_round_type       114949 non-null  object
 3   funding_round_code       31140 non-null   object
 4   funded_at                114949 non-null  object
 5   raised_amount_usd        94959 non-null   float64
dtypes: float64(1), object(5)
memory usage: 5.3+ MB

In [15]:
rounds2['company_permalink'] = rounds2['company_permalink'].apply(lambda x:str(x).lower())
rounds2.sample(20)

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
47611,/organization/infonow,/funding-round/a3d0e0d691551a1f7e24677b91e0f3f7,venture,NaN,14-01-2011,6807031.0
94162,/organization/sprout-foods,/funding-round/73ce0dc84c583c9ce018a38eec9e336d,venture,NaN,01-12-2011,4169864.0
52097,/organization/kaltura,/funding-round/6ff90875d9159b89aa6545d23f32695d,venture,B,20-06-2008,21000000.0
70200,/organization/omniture,/funding-round/d00e5105d492ec2484f9d47094b70279,secondary_market,NaN,01-01-2006,NaN
62485,/organization/missingames,/funding-round/18277478dbf0a4eb912db0c3f5da24af,seed,NaN,01-02-2014,20265.0
54507,/organization/lantos-technologies,/funding-round/556e945d12e68850be9deb8e932411e8,debt_financing,NaN,05-10-2015,3922126.0
96149,/organization/superdimension,/funding-round/91906cd45b01fb057505ace84b76150f,venture,NaN,12-09-2011,11000000.0
39833,/organization/gigsky,/funding-round/bb0716f792f85be375d581233a59929a,venture,NaN,22-04-2015,3050000.0
12768,/organization/bitpass,/funding-round/60ea958648f59dc6ef72a99d87b03aec,venture,A,01-07-2003,1500000.0
113963,/organization/zeplin,/funding-round/01c3a61ef5214d42d3d63878e073ac37,seed,NaN,20-07-2015,120000.0
27222,/organization/desktop-genetics,/funding-round/7f398e4c9613f75c414e2253aa3c687a,venture,NaN,15-09-2015,2156444.0
67716,/organization/nextcare,/funding-round/497e8a3085b0dabe61ebc9243fef0b9a,venture,NaN,05-10-2010,2500000.0
44120,/organization/high-performance-smartebuilding,/funding-round/45a9e94940e27018f5a8c4a7795935ae,venture,NaN,03-06-2009,435000.0
28100,/organization/disksites-inc,/funding-round/5eb672dd8a71e8570e8c6fd343e23b5f,venture,NaN,04-04-2001,3200000.0
91763,/organization/social-tables,/funding-round/e99e082fe775ecebfc52c10f4e7c1d2d,seed,NaN,22-05-2012,500000.0
94538,/organization/starboard-resources,/funding-round/0859a349dab4461382f557cb0cded849,venture,NaN,06-10-2010,NaN
3386,/organization/agenda,/funding-round/a841da1912aeb233f2338bcc3bf599a3,seed,NaN,01-07-2013,102117.0
81477,/organization/rayneer,/funding-round/b1c558a44642cc43cfe651882f375094,seed,NaN,30-11-2011,120000.0
38851,/organization/geckogo,/funding-round/caaef27112288e12826b8f5c1dec4a60,seed,NaN,01-06-2009,NaN
76174,/organization/plasticell,/funding-round/4774b2031bf880828aa6f9dc21e82b91,venture,NaN,23-11-2007,1418703.0

In [16]:
print(rounds2['company_permalink'].nunique())

66370

In [17]:
rounds2

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/organization/-qounter,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/organization/-the-one-of-them-inc-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0
...,...,...,...,...,...,...
114944,/organization/zzzzapp-com,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,NaN,01-03-2014,41313.0
114945,/organization/zzzzapp-com,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,NaN,01-05-2013,32842.0
114946,/organization/ãeron,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN
114947,/organization/ãasys-2,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0
114948,/organization/ä°novatiff-reklam-ve-tanä±tä±m-h...,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0

In [18]:
master_frame = pd.merge(rounds2,companies,left_on='company_permalink',right_on='permalink')
print(master_frame.shape)
master_frame.tail(50)

(114942, 16)

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
114892,/organization/zymr-inc-,/funding-round/9048d1a80edeae803ed1790c9f473eec,angel,NaN,12-12-2012,NaN,/organization/zymr-inc-,"Zymr, Inc.",http://www.zymr.com,Android|Apps|Cloud Computing|Cloud Infrastruct...,operating,USA,CA,SF Bay Area,Santa Clara,NaN
114893,/organization/zyncd,/funding-round/3549f5a481f83610044a4226926acf5a,venture,NaN,01-09-2014,144451.0,/organization/zyncd,Zyncd,http://www.zyncd.com,Crowdsourcing|Knowledge Management,operating,GBR,H9,London,London,01-01-2014
114894,/organization/zyncd,/funding-round/5a0d321abcfef61a8bae383176ac46e7,seed,NaN,01-02-2014,54042.0,/organization/zyncd,Zyncd,http://www.zyncd.com,Crowdsourcing|Knowledge Management,operating,GBR,H9,London,London,01-01-2014
114895,/organization/zyncro,/funding-round/35310bcb0945d9d4b5ffa5482e5c87f3,venture,B,03-02-2012,2105600.0,/organization/zyncro,Zyncro,http://www.zyncro.com,Cloud Computing|Enterprise 2.0|Enterprise Soft...,acquired,ESP,56,Barcelona,Barcelona,01-09-2009
114896,/organization/zyncro,/funding-round/c8dd9ae33cc5d5a1d972b470a5955373,venture,A,05-04-2011,1699920.0,/organization/zyncro,Zyncro,http://www.zyncro.com,Cloud Computing|Enterprise 2.0|Enterprise Soft...,acquired,ESP,56,Barcelona,Barcelona,01-09-2009
114897,/organization/zynerba-pharmaceuticals,/funding-round/8992160f6abc8e21563e54a6e97a8922,venture,NaN,14-10-2014,13000000.0,/organization/zynerba-pharmaceuticals,Zynerba Pharmaceuticals,http://zynerba.com,Pharmaceuticals,ipo,USA,PA,Philadelphia,Radnor,01-01-2014
114898,/organization/zynergy-projects-services,/funding-round/3d7dbd2d92220d93e2b5455f914a0918,venture,NaN,19-08-2015,NaN,/organization/zynergy-projects-services,Zynergy Projects & Services,http://www.zynergygroup.net/,Clean Technology,operating,IND,25,Chennai,Chennai,NaN
114899,/organization/zynga,/funding-round/1bc4f7b3a778e5abfbd7131f595f5011,venture,B,04-11-2009,15187000.0,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114900,/organization/zynga,/funding-round/5bebd7acdfd44138f81d162f21c532f9,venture,NaN,12-10-2010,6337786.0,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114901,/organization/zynga,/funding-round/66d64809546fe2031d3479161e3c88f9,venture,A,01-01-2008,10000000.0,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114902,/organization/zynga,/funding-round/72e4fdf2cfb0cdc0750f90e486722068,venture,B,18-07-2008,25000000.0,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114903,/organization/zynga,/funding-round/8411431b5a0389a874e3fae93016c089,venture,B,24-04-2010,15000000.0,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114904,/organization/zynga,/funding-round/a6ebc53cf3c0c97d1cdd075f6bbf31fa,venture,C,18-02-2011,490000000.0,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114905,/organization/zynga,/funding-round/cf8299f657f7fd4cf01054ee1934109c,venture,B,14-06-2010,300000000.0,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114906,/organization/zynga,/funding-round/d27f10a20b15b4ef3d9961d54eabf6b1,angel,NaN,01-01-2007,NaN,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114907,/organization/zynga,/funding-round/eb198261da812bc8d3bf475ccec44000,venture,A,12-02-2008,5026000.0,/organization/zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
114908,/organization/zyngenia,/funding-round/55ec03b6fa2e812a2b4a9da5a4555752,venture,A,09-09-2010,25000000.0,/organization/zyngenia,Zyngenia,http://www.zyngenia.com,Biotechnology,operating,USA,MD,"Washington, D.C.",Gaithersburg,01-01-2008
114909,/organization/zynstra,/funding-round/05f43b37c270f5919578281ce803de8f,venture,B,09-07-2014,8400000.0,/organization/zynstra,Zynstra,http://www.zynstra.com,Software,operating,GBR,A4,Bath,Bath,30-11-2011
114910,/organization/zynstra,/funding-round/129127802dd48be42d6cd45f65895245,venture,A,12-09-2013,3800000.0,/organization/zynstra,Zynstra,http://www.zynstra.com,Software,operating,GBR,A4,Bath,Bath,30-11-2011
114911,/organization/zynstra,/funding-round/6c01f0a76c1341118d63b670ac841bd9,seed,NaN,03-03-2012,225000.0,/organization/zynstra,Zynstra,http://www.zynstra.com,Software,operating,GBR,A4,Bath,Bath,30-11-2011
114912,/organization/zynstra,/funding-round/dee233b3434185c14b3352034f72d798,angel,NaN,18-09-2012,2325000.0,/organization/zynstra,Zynstra,http://www.zynstra.com,Software,operating,GBR,A4,Bath,Bath,30-11-2011
114913,/organization/zyomyx-inc,/funding-round/4191cb5258d3863b0212d1083881da64,venture,B,30-06-2013,12000000.0,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114914,/organization/zyomyx-inc,/funding-round/85443f5438bfd50104b9591eabc95c94,grant,NaN,26-03-2014,7500000.0,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114915,/organization/zyomyx-inc,/funding-round/b4fce7f8a13267353d57db09099800e8,venture,NaN,11-07-2013,14219999.0,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114916,/organization/zyomyx-inc,/funding-round/ea5b21da6cf999ff4d5667431fe318d7,venture,NaN,29-01-2010,555016.0,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
114917,/organization/zype,/funding-round/24e8134882bf6c4dcc385abba0acd5d9,seed,NaN,01-04-2015,1700000.0,/organization/zype,Zype,http://www.zype.com,Cloud Computing|Mobile Advertising|Video|Video...,operating,USA,NY,New York City,New York,01-01-2013
114918,/organization/zype,/funding-round/c9f5097b3617c7539aa47c8b448163be,seed,NaN,27-10-2015,1600000.0,/organization/zype,Zype,http://www.zype.com,Cloud Computing|Mobile Advertising|Video|Video...,operating,USA,NY,New York City,New York,01-01-2013
114919,/organization/zypsee,/funding-round/472c6f7940522552fcca465b8cd3deef,seed,NaN,25-09-2013,2150000.0,/organization/zypsee,Whisk (formerly Zypsee),http://whisk.me,Public Transportation,operating,USA,NY,New York City,New York,01-01-2011
114920,/organization/zypsee,/funding-round/c67e22c5448435adaf5a2d101e449dde,seed,NaN,26-07-2013,NaN,/organization/zypsee,Whisk (formerly Zypsee),http://whisk.me,Public Transportation,operating,USA,NY,New York City,New York,01-01-2011
114921,/organization/zyraz-technology,/funding-round/3c3ae0f177e01a04deea811e1828be35,private_equity,NaN,15-02-2013,20967.0,/organization/zyraz-technology,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114922,/organization/zyraz-technology,/funding-round/55f33b179dd6f4516315348c1e8350c6,angel,NaN,01-01-2008,2007363.0,/organization/zyraz-technology,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114923,/organization/zyraz-technology,/funding-round/c05aab2155e390066d51c6852ff61464,grant,NaN,11-09-2009,5400000.0,/organization/zyraz-technology,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114924,/organization/zyraz-technology,/funding-round/e949f077c943db197f20e43c2eb8d0e6,venture,A,09-10-2009,7991547.0,/organization/zyraz-technology,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
114925,/organization/zyrra,/funding-round/2a13fa52848ace2760b224a350a76b40,seed,NaN,15-11-2010,445000.0,/organization/zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
114926,/organization/zyrra,/funding-round/39baf35e59eb3efc5409cd4c5eaa50e1,seed,NaN,21-10-2010,50000.0,/organization/zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
114927,/organization/zyrra,/funding-round/7a0fa791c96c9c447ee54662395beab9,venture,NaN,18-10-2012,140500.0,/organization/zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
114928,/organization/zyrra,/funding-round/cc8cd96a500332d5b4f4bcbddb306099,angel,NaN,15-12-2010,875000.0,/organization/zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
114929,/organization/zystor,/funding-round/7ea37c0ff4132b084832039a9380d34e,venture,A,16-12-2004,8500000.0,/organization/zystor,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN
114930,/organization/zytoprotec,/funding-round/0c43e717298296d2fb334fb236300f6e,venture,A,29-01-2013,2686600.0,/organization/zytoprotec,Zytoprotec,http://www.zytoprotec.com,Biotechnology,operating,AUT,3,Vienna,Gerasdorf Bei Wien,01-01-2007
114931,/organization/zzish,/funding-round/34b560f672bebeb339a5efa3b27eae5d,grant,NaN,25-02-2015,400000.0,/organization/zzish,Zzish,http://www.zzish.com,Analytics|Android|Developer APIs|Education|Gam...,operating,GBR,H9,London,London,28-01-2014
114932,/organization/zzish,/funding-round/4c82e18a8e3eab2647719d0fc27ead5f,angel,NaN,31-10-2014,400000.0,/organization/zzish,Zzish,http://www.zzish.com,Analytics|Android|Developer APIs|Education|Gam...,operating,GBR,H9,London,London,28-01-2014
114933,/organization/zzish,/funding-round/73721fffc980d228f051e87422aa8732,seed,NaN,24-03-2014,320000.0,/organization/zzish,Zzish,http://www.zzish.com,Analytics|Android|Developer APIs|Education|Gam...,operating,GBR,H9,London,London,28-01-2014
114934,/organization/zznode-science-and-technology-co...,/funding-round/171693e1e07e0230defd8fddb6de4515,venture,A,01-04-2012,1587301.0,/organization/zznode-science-and-technology-co...,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,operating,CHN,22,Beijing,Beijing,NaN
114935,/organization/zzzzapp-com,/funding-round/22ef2fafb4d20ac3aa4b86143dbf6c8e,seed,NaN,01-11-2011,7000.0,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114936,/organization/zzzzapp-com,/funding-round/6ba41360588bc6e3f77e9b50a0ebfafa,seed,NaN,01-08-2013,33149.0,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114937,/organization/zzzzapp-com,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,NaN,01-03-2014,41313.0,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114938,/organization/zzzzapp-com,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,NaN,01-05-2013,32842.0,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
114939,/organization/ãeron,/funding-round/59f4dce44723b794f21ded3daed6e4fe,venture,A,01-08-2014,NaN,/organization/ãeron,ÃERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN,01-01-2011
114940,/organization/ãasys-2,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,NaN,01-01-2015,18192.0,/organization/ãasys-2,Ãasys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
114941,/organization/ä°novatiff-reklam-ve-tanä±tä±m-h...,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,NaN,01-10-2013,14851.0,/organization/ä°novatiff-reklam-ve-tanä±tä±m-h...,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN

In [19]:
master_frame.isnull().sum()

company_permalink              0
funding_round_permalink        0
funding_round_type             0
funding_round_code         83803
funded_at                      0
raised_amount_usd          19984
permalink                      0
name                           1
homepage_url                6132
category_list               3407
status                         0
country_code                8671
state_code                 10939
region                     10160
city                       10157
founded_at                 20520
dtype: int64

In [20]:
round(100*(master_frame.isnull().sum()/len(master_frame.index)), 2)

company_permalink           0.00
funding_round_permalink     0.00
funding_round_type          0.00
funding_round_code         72.91
funded_at                   0.00
raised_amount_usd          17.39
permalink                   0.00
name                        0.00
homepage_url                5.33
category_list               2.96
status                      0.00
country_code                7.54
state_code                  9.52
region                      8.84
city                        8.84
founded_at                 17.85
dtype: float64

In [21]:
master_frame=master_frame.drop('funding_round_code',axis=1)
master_frame=master_frame=master_frame.drop('founded_at',axis=1)
master_frame=master_frame.drop('company_permalink',axis=1)
master_frame.isnull().sum()

funding_round_permalink        0
funding_round_type             0
funded_at                      0
raised_amount_usd          19984
permalink                      0
name                           1
homepage_url                6132
category_list               3407
status                         0
country_code                8671
state_code                 10939
region                     10160
city                       10157
dtype: int64

In [22]:
round(100*(master_frame.isnull().sum())/len(master_frame.index),2)

funding_round_permalink     0.00
funding_round_type          0.00
funded_at                   0.00
raised_amount_usd          17.39
permalink                   0.00
name                        0.00
homepage_url                5.33
category_list               2.96
status                      0.00
country_code                7.54
state_code                  9.52
region                      8.84
city                        8.84
dtype: float64

In [23]:
master_frame['raised_amount_usd'].isnull().sum()

19984

In [24]:
master_frame.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            114932, 114933, 114934, 114935, 114936, 114937, 114938, 114939,
            114940, 114941],
           dtype='int64', length=114942)

In [25]:
master_frame = master_frame[~master_frame['raised_amount_usd'].isnull()]
round(100*(master_frame.isnull().sum())/len(master_frame.index),2)

funding_round_permalink    0.00
funding_round_type         0.00
funded_at                  0.00
raised_amount_usd          0.00
permalink                  0.00
name                       0.00
homepage_url               4.56
category_list              1.10
status                     0.00
country_code               6.16
state_code                 8.01
region                     7.42
city                       7.42
dtype: float64

In [26]:
master_frame = master_frame.drop('homepage_url',axis=1)
master_frame = master_frame.drop('state_code',axis=1)
master_frame = master_frame.drop('city',axis=1)
master_frame = master_frame.drop('region',axis=1)

In [27]:
round(100*(master_frame.isnull().sum())/len(master_frame.index),2)

funding_round_permalink    0.00
funding_round_type         0.00
funded_at                  0.00
raised_amount_usd          0.00
permalink                  0.00
name                       0.00
category_list              1.10
status                     0.00
country_code               6.16
dtype: float64

In [28]:
master_frame

,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,permalink,name,category_list,status,country_code
0,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0,/organization/-fame,#fame,Media,operating,IND
2,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,01-03-2014,700000.0,/organization/-qounter,:Qounter,Application Platforms|Real Time|Social Network...,operating,USA
3,/funding-round/650b8f704416801069bb178a1418776b,venture,30-01-2014,3406878.0,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",Apps|Games|Mobile,operating,NaN
4,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,19-03-2008,2000000.0,/organization/0-6-com,0-6.com,Curated Web,operating,CHN
6,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,undisclosed,01-07-2014,41250.0,/organization/01games-technology,01Games Technology,Games,operating,HKG
...,...,...,...,...,...,...,...,...,...
114936,/funding-round/6ba41360588bc6e3f77e9b50a0ebfafa,seed,01-08-2013,33149.0,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,Advertising|Mobile|Web Development|Wireless,operating,HRV
114937,/funding-round/8f6d25b8ee4199e586484d817bceda05,convertible_note,01-03-2014,41313.0,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,Advertising|Mobile|Web Development|Wireless,operating,HRV
114938,/funding-round/ff1aa06ed5da186c84f101549035d4ae,seed,01-05-2013,32842.0,/organization/zzzzapp-com,Zzzzapp Wireless ltd.,Advertising|Mobile|Web Development|Wireless,operating,HRV
114940,/funding-round/35f09d0794651719b02bbfd859ba9ff5,seed,01-01-2015,18192.0,/organization/ãasys-2,Ãasys,Consumer Electronics|Internet of Things|Teleco...,operating,USA
114941,/funding-round/af942869878d2cd788ef5189b435ebc4,grant,01-10-2013,14851.0,/organization/ä°novatiff-reklam-ve-tanä±tä±m-h...,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,Consumer Goods|E-Commerce|Internet,operating,NaN

In [29]:
fund_rtyp = master_frame.groupby('funding_round_type')
fund_rtyp

In [30]:
fund_rtyp.describe()

                      raised_amount_usd                                       \
                                  count          mean           std      min
funding_round_type
angel                            4860.0  9.586945e+05  7.404397e+06      0.0
convertible_note                 1447.0  1.453439e+06  8.043846e+06      0.0
debt_financing                   6682.0  1.704353e+07  2.803204e+08      0.0
equity_crowdfunding              1228.0  5.383682e+05  1.719329e+06      0.0
grant                            2124.0  4.300576e+06  2.558742e+07      0.0
non_equity_assistance              73.0  4.112031e+05  1.771747e+06      0.0
post_ipo_debt                     152.0  1.687046e+08  6.024738e+08  70000.0
post_ipo_equity                   628.0  8.218249e+07  4.691889e+08     77.0
private_equity                   1936.0  7.330859e+07  1.981135e+08      0.0
product_crowdfunding              386.0  1.363131e+06  4.698380e+06      0.0
secondary_market                   30.0  7.964963e+07  1.401038e+08   2323.0
seed                            23602.0  7.197796e+05  2.221772e+06      0.0
undisclosed                      1582.0  1.924237e+07  1.993238e+08      0.0
venture                         50228.0  1.174895e+07  8.635207e+07      0.0


                              25%         50%         75%           max
funding_round_type
angel                   150000.00    400000.0   1000000.0  4.945120e+08
convertible_note         78847.50    272000.0   1000000.0  1.850483e+08
debt_financing          330484.25   1100000.0   4000000.0  2.127194e+10
equity_crowdfunding       7000.00    100000.0    395901.0  2.740000e+07
grant                    50000.00    201684.0   1700000.0  7.500000e+08
non_equity_assistance    25000.00     60000.0    125000.0  1.500000e+07
post_ipo_debt          4000000.00  19950000.0  60000000.0  5.800000e+09
post_ipo_equity        3764794.00  12262852.5  40000000.0  1.066494e+10
private_equity         5000000.00  20000000.0  75000000.0  4.745460e+09
product_crowdfunding     40241.75    183915.0    735000.0  5.200000e+07
secondary_market       5025000.00  32600000.0  84475000.0  6.806116e+08
seed                     55000.00    275000.0   1000000.0  2.000000e+08
undisclosed             220000.00   1018680.0   4848804.0  5.000000e+09
venture                1600901.75   5000000.0  12000000.0  1.760000e+10

In [31]:
fund_rtyp['raised_amount_usd'].median()

funding_round_type
angel                      400000.0
convertible_note           272000.0
debt_financing            1100000.0
equity_crowdfunding        100000.0
grant                      201684.0
non_equity_assistance       60000.0
post_ipo_debt            19950000.0
post_ipo_equity          12262852.5
private_equity           20000000.0
product_crowdfunding       183915.0
secondary_market         32600000.0
seed                       275000.0
undisclosed               1018680.0
venture                   5000000.0
Name: raised_amount_usd, dtype: float64

In [32]:
fund_rtyp['raised_amount_usd'].mean()

funding_round_type
angel                    9.586945e+05
convertible_note         1.453439e+06
debt_financing           1.704353e+07
equity_crowdfunding      5.383682e+05
grant                    4.300576e+06
non_equity_assistance    4.112031e+05
post_ipo_debt            1.687046e+08
post_ipo_equity          8.218249e+07
private_equity           7.330859e+07
product_crowdfunding     1.363131e+06
secondary_market         7.964963e+07
seed                     7.197796e+05
undisclosed              1.924237e+07
venture                  1.174895e+07
Name: raised_amount_usd, dtype: float64

In [41]:
master_frame['country_code'].isnull().sum()

5850

In [42]:
master_frame= master_frame[~master_frame['country_code'].isnull()]
master_frame['country_code'].isnull().sum()

0

In [53]:
country= master_frame.groupby('country_code')

In [46]:
country.mean()

              raised_amount_usd
country_code
ALB                1.383720e+05
ARE                1.635645e+07
ARG                1.220052e+06
ARM                6.704375e+06
AUS                5.915619e+06
...                         ...
VEN                1.321217e+05
VNM                1.485854e+07
ZAF                1.513820e+07
ZMB                2.600000e+05
ZWE                5.015000e+06

[134 rows x 1 columns]

In [59]:
print(country.median())
country.sum()

              raised_amount_usd
country_code
ALB                    138372.0
ARE                    475000.0
ARG                     59873.0
ARM                   3965000.0
AUS                    930960.0
...                         ...
VEN                     68230.5
VNM                   3500000.0
ZAF                    457000.0
ZMB                    260000.0
ZWE                   5015000.0

[134 rows x 1 columns]

              raised_amount_usd
country_code
ALB                2.767440e+05
ARE                1.570219e+09
ARG                3.623555e+08
ARM                2.681750e+07
AUS                3.839237e+09
...                         ...
VEN                2.642434e+06
VNM                4.011805e+08
ZAF                1.074812e+09
ZMB                5.200000e+05
ZWE                1.003000e+07

[134 rows x 1 columns]

In [61]:
top9 = country.sum().sort_values(by='raised_amount_usd',ascending=False).head(9)
top9

              raised_amount_usd
country_code
USA                6.694821e+11
CHN                7.570357e+10
GBR                3.276705e+10
IND                2.768634e+10
CAN                1.842468e+10
RUS                1.127912e+10
DEU                1.001776e+10
ISR                9.713885e+09
FRA                9.059771e+09

In [62]:
mapping = pd.read_csv('mapping.csv')
mapping

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
0,NaN,0,1,0,0,0,0,0,0,0
1,3D,0,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
683,Wholesale,0,0,0,0,0,0,0,1,0
684,Wine And Spirits,0,0,0,1,0,0,0,0,0
685,Wireless,0,0,0,1,0,0,0,0,0
686,Women,0,0,0,0,0,0,0,1,0
687,Young Adults,0,0,0,0,0,0,0,1,0

In [64]:
mapping.columns

Index(['category_list', 'Automotive & Sports', 'Blanks',
       'Cleantech / Semiconductors', 'Entertainment', 'Health',
       'Manufacturing', 'News, Search and Messaging', 'Others',
       'Social, Finance, Analytics, Advertising'],
      dtype='object')

In [66]:
mapping.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688 entries, 0 to 687
Data columns (total 10 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   category_list                            687 non-null    object
 1   Automotive & Sports                      688 non-null    int64
 2   Blanks                                   688 non-null    int64
 3   Cleantech / Semiconductors               688 non-null    int64
 4   Entertainment                            688 non-null    int64
 5   Health                                   688 non-null    int64
 6   Manufacturing                            688 non-null    int64
 7   News, Search and Messaging               688 non-null    int64
 8   Others                                   688 non-null    int64
 9   Social, Finance, Analytics, Advertising  688 non-null    int64
dtypes: int64(9), object(1)
memory usage: 53.9+ KB

In [65]:
mapping['category_list'].values

array([nan, '3D', '3D Printing', '3D Technology', 'Accounting',
       'Active Lifestyle', 'Ad Targeting', 'Advanced Materials',
       'Adventure Travel', 'Advertising', 'Advertising Exchanges',
       'Advertising Networks', 'Advertising Platforms', 'Advice',
       'Aerospace', 'Agriculture', 'Air Pollution Control', 'Algorithms',
       'All Markets', 'All Students', 'Alter0tive Medicine', 'Alumni',
       'A0lytics', 'Android', 'Angels', 'Animal Feed',
       'Anything Capital Intensive', 'App Discovery', 'App Marketing',
       'App Stores', 'Application Performance Monitoring',
       'Application Platforms', 'Apps', 'Aquaculture', 'Architecture',
       'Archiving', 'Art', 'Artificial Intelligence', 'Artists Globally',
       'Assisitive Technology', 'Assisted Living', 'Auctions', 'Audio',
       'Audiobooks', 'Augmented Reality', 'Auto', 'Automated Kiosk',
       'Automotive', 'B2B', 'B2B Express Delivery', 'Babies',
       'Baby Accessories', 'Baby Boomers', 'Baby Safety', 'Banking',
       'Batteries', 'Beauty', 'Bicycles', 'Big Data', 'Big Data A0lytics',
       'Billing', 'Bio-Pharm', 'Biofuels', 'Bioinformatics',
       'Biomass Power Generation', 'Biometrics', 'Biotechnology',
       'Bitcoin', 'Blogging Platforms', 'Boating Industry',
       'BPO Services', 'Brand Marketing', 'Brewing',
       'Bridging Online and Offline', 'Broadcasting', 'Brokers',
       'Browser Extensions', 'Building Owners', 'Building Products',
       'Business A0lytics', 'Business Development',
       'Business Information Systems', 'Business Intelligence',
       'Business Productivity', 'Business Services', 'Business Travelers',
       'Cable', 'CAD', 'Call Center Automation', 'Can0bis', 'Carbon',
       'Career Ma0gement', 'Career Planning', 'Cars', 'Casual Games',
       'Celebrity', 'Certification Test', 'Charities', 'Charity',
       'Charter Schools', 'Chat', 'Chemicals', 'Child Care',
       'Chi0 Internet', 'Civil Engineers', 'Classifieds', 'Clean Energy',
       'Clean Technology', 'Clean Technology IT', 'Clinical Trials',
       'Cloud-Based Music', 'Cloud Computing', 'Cloud Data Services',
       'Cloud Infrastructure', 'Cloud Ma0gement', 'Cloud Security',
       'Coffee', 'Collaboration', 'Collaborative Consumption',
       'Collectibles', 'College Campuses', 'College Recruiting',
       'Colleges', 'Comics', 'Commercial Real Estate', 'Commercial Solar',
       'Commodities', 'Communications Hardware',
       'Communications Infrastructure', 'Communities',
       'Comparison Shopping', 'Computer Vision', 'Computers',
       'Concentrated Solar Power', 'Concerts', 'Console Gaming',
       'Construction', 'Consulting', 'Consumer Behavior',
       'Consumer Electronics', 'Consumer Goods', 'Consumer Internet',
       'Consumer Lending', 'Consumers', 'Contact Centers',
       'Contact Ma0gement', 'Content', 'Content Creators',
       'Content Delivery', 'Content Discovery', 'Content Syndication',
       'Contests', 'Cooking', 'Corporate IT', 'Corporate Training',
       'Corporate Wellness', 'Cosmetic Surgery', 'Cosmetics', 'Coupons',
       'Coworking', 'Craft Beer', 'Creative', 'Creative Industries',
       'Credit', 'Credit Cards', 'CRM', 'Crowdfunding', 'Crowdsourcing',
       'Curated Web', 'Custom Retail', 'Customer Service',
       'Customer Support Tools', 'Cyber', 'Cyber Security',
       'Data Center Automation', 'Data Center Infrastructure',
       'Data Centers', 'Data Integration', 'Data Mining', 'Data Privacy',
       'Data Security', 'Data Visualization', 'Databases',
       'Debt Collecting', 'Defense', 'Delivery', 'Demographies', 'Dental',
       'Design', 'Designers', 'Developer APIs', 'Developer Tools',
       'Development Platforms', 'Diabetes', 'Diagnostics',
       'Dietary Supplements', 'Digital Entertainment', 'Digital Media',
       'Digital Rights Ma0gement', 'Digital Sig0ge', 'Direct Advertising',
       'Direct Marketing', 'Direct Sales', 'Discounts', 'Displays',
       'Disruptive Models', 'Distribution', 'Distributors', 'DIY',
       'Doctors', 'Document Ma0gement', 'DOD/Military', 'Domains',
       'Drones', 'E-Books', 'E-Commerce', 'E-Commerce Platforms',
       'Early-Stage Technology', 'EBooks', 'EDA Tools', 'Ediscovery',
       'EdTech', 'Education', 'Educatio0l Games', 'Edutainment',
       'Elder Care', 'Electric Vehicles', 'Electrical Distribution',
       'Electronic Health Records', 'Electronics', 'Email',
       'Email Marketing', 'Email Newsletters',
       'Embedded Hardware and Software', 'Emerging Markets',
       'Employer Benefits Programs', 'Employment', 'Energy',
       'Energy Efficiency', 'Energy IT', 'Energy Ma0gement',
       'Energy Storage', 'Engineering Firms', 'Enterprise 2.0',
       'Enterprise Application', 'Enterprise Purchasing',
       'Enterprise Resource Planning', 'Enterprise Search',
       'Enterprise Security', 'Enterprise Software', 'Enterprises',
       'Entertainment', 'Entertainment Industry', 'Entrepreneur',
       'Environmental Innovation', 'Estimation and Quoting',
       'Event Ma0gement', 'Events', 'Exercise', 'Eyewear',
       'Face Recognition', 'Facebook Applications', 'Families',
       'Fantasy Sports', 'Farmers Market', 'Farming', 'Fashion',
       'Fertility', 'Field Support Services', 'File Sharing', 'Film',
       'Film Distribution', 'Film Production', 'Fi0nce',
       'Fi0nce Technology', 'Fi0ncial Exchanges', 'Fi0ncial Services',
       'FinTech', 'Fitness', 'Flash Sales', 'Flash Storage',
       'Fleet Ma0gement', 'Flowers', 'Fmcg', 'Food Processing', 'Forums',
       'Fraud Detection', 'Freelancers', 'Freemium', 'FreetoPlay Gaming',
       'Fruit', 'Fuel Cells', 'Fuels', 'Funeral Industry', 'Furniture',
       'Gadget', 'Gambling', 'Game', 'Game Mechanics', 'Games',
       'Gamification', 'Gas', 'Gay & Lesbian', 'General Public Worldwide',
       'Genetic Testing', 'Geospatial', 'Gift Card', 'Gift Exchange',
       'Gift Registries', 'Gold', 'Gover0nce', 'Government Innovation',
       'Governments', 'Gps', 'Graphics', 'Green', 'Green Consumer Goods',
       'Groceries', 'Group Buying', 'Group SMS', 'Guides', 'Handmade',
       'Hardware', 'Hardware + Software', 'Health and Insurance',
       'Health and Wellness', 'Health Care',
       'Health Care Information Technology', 'Health Diagnostics',
       'Health Services Industry', 'Healthcare Services',
       'Heavy Industry', 'Hedge Funds', 'High School Students',
       'High Schools', 'High Tech', 'Home & Garden', 'Home Automation',
       'Home Decor', 'Home Owners', 'Home Renovation',
       'Homeland Security', 'Homeless Shelter', 'Hospitality',
       'Hospitals', 'Hotels', 'Human Computer Interaction',
       'Human Resource Automation', 'Human Resources', 'Humanitarian',
       'IaaS', 'ICT', 'Identity', 'Identity Ma0gement',
       'Image Recognition', 'Impact Investing', 'In-Flight Entertainment',
       'Incentives', 'Incubators', 'Independent Music Labels',
       'Independent Pharmacies', 'Indians', 'Indoor Positioning',
       'Industrial', 'Industrial Automation', 'Information Security',
       'Information Services', 'Information Technology', 'Infrastructure',
       'Innovation Engineering', 'Innovation Ma0gement', 'Insurance',
       'Intellectual Asset Ma0gement', 'Intellectual Property',
       'Intelligent Systems', 'Interest Graph', 'Interface Design',
       'Interior Design', 'Internet', 'Internet Infrastructure',
       'Internet Marketing', 'Internet of Things',
       'Internet Radio Market', 'Internet Service Providers',
       'Investment Ma0gement', 'iOS', 'iPad', 'iPhone',
       'IT and Cybersecurity', 'IT Ma0gement', 'Jewelry', 'Jour0lism',
       'K-12 Education', 'Kids', 'Knowledge Ma0gement', 'Landscaping',
       'Language Learning', 'Lasers', 'Law Enforcement',
       'Lead Generation', 'Lead Ma0gement', 'Legal', 'Leisure',
       'Licensing', 'Life Sciences', 'Lifestyle', 'Lifestyle Businesses',
       'Lifestyle Products', 'Lighting', 'Limousines', 'Linux', 'Local',
       'Local Advertising', 'Local Based Services', 'Local Businesses',
       'Local Commerce', 'Local Search', 'Location Based Services',
       'Logistics', 'Logistics Company', 'Lotteries', 'Low Bid Auctions',
       'Loyalty Programs', 'M2M', 'Machine Learning', 'Manufacturing',
       'Maps', 'Market Research', 'Marketing Automation', 'Marketplaces',
       'Mass Customization', 'Match-Making', 'Material Science',
       'Mechanical Solutions', 'Media', 'Medical', 'Medical Devices',
       'Medical Professio0ls', 'Meeting Software', 'Mens Specific',
       'Messaging', 'mHealth', 'Micro-Enterprises', 'MicroBlogging',
       'Minerals', 'Mining Technologies', 'Mobile', 'Mobile Advertising',
       'Mobile A0lytics', 'Mobile Commerce', 'Mobile Devices',
       'Mobile Enterprise', 'Mobile Games', 'Mobile Health',
       'Mobile Infrastructure', 'Mobile Payments', 'Mobile Security',
       'Mobile Shopping', 'Mobile Social', 'Mobile Software Tools',
       'Mobile Video', 'Mobility', 'Monetization', 'Moneymaking',
       'Multi-level Marketing', 'Music', 'Music Education',
       'Music Services', 'Music Venues', 'Musical Instruments',
       'Musicians', '0notechnology', '0tural Language Processing',
       '0tural Resources', '0vigation', 'Network Security', 'Networking',
       'Neuroscience', 'New Product Development', 'New Technologies',
       'News', 'Non-Tech', 'Non Profit', 'Nonprofits', 'Nutrition',
       'Office Space', 'Oil', 'Oil & Gas', 'Oil and Gas', 'Online Dating',
       'Online Education', 'Online Gaming', 'Online Identity',
       'Online Rental', 'Online Reservations', 'Online Scheduling',
       'Online Shopping', 'Online Travel', 'Online Video Advertising',
       'Open Source', 'Opinions', 'Optical Communications',
       'Optimization', 'Organic', 'Organic Food', 'Outdoors',
       'Outsourcing', 'P2P Money Transfer', 'PaaS', 'Parenting',
       'Parking', 'Payments', 'Peer-to-Peer', 'Performance Marketing',
       'Perso0l Branding', 'Perso0l Data', 'Perso0l Fi0nce',
       'Perso0l Health', 'Perso0lization', 'Pervasive Computing', 'Pets',
       'Pharmaceuticals', 'Photo Editing', 'Photo Sharing', 'Photography',
       'Physical Security', 'Physicians', 'Plumbers', 'Point of Sale',
       'Politics', 'Polling', 'Portals', 'Postal and Courier Services',
       'Pre Seed', 'Predictive A0lytics', 'Presentations',
       'Price Comparison', 'Printing', 'Privacy', 'Private School',
       'Private Social Networking', 'Procurement', 'Product Design',
       'Product Development Services', 'Productivity',
       'Productivity Software', 'Professio0l Networking',
       'Professio0l Services', 'Project Ma0gement', 'Promotio0l',
       'Property Ma0gement', 'Public Relations', 'Public Safety',
       'Public Transportation', 'Publishing', 'Q&A', 'QR Codes',
       'Real Estate', 'Real Time', 'Realtors', 'Recreation', 'Recruiting',
       'Recycling', 'Religion', 'Renewable Energies', 'Renewable Tech',
       'Rental Housing', 'Reputation', 'Resorts', 'Restaurants', 'Retail',
       'Retail Technology', 'Reviews and Recommendations', 'RFID',
       'Ride Sharing', 'Risk Ma0gement', 'Robotics', 'SaaS',
       'Sales and Marketing', 'Sales Automation', 'Search',
       'Search Marketing', 'Security',
       'Semiconductor Manufacturing Equipment', 'Semiconductors',
       'Senior Citizens', 'Senior Health', 'Sensors', 'SEO',
       'Service Industries', 'Service Providers', 'Services', 'SexTech',
       'Shared Services', 'Shipping', 'Shoes', 'Shopping', 'Simulation',
       'Skill Assessment', 'Small and Medium Businesses', 'Smart Grid',
       'SNS', 'Soccer', 'Social + Mobile + Local', 'Social Bookmarking',
       'Social Business', 'Social Buying', 'Social Commerce',
       'Social CRM', 'Social Fundraising', 'Social Games', 'Social Media',
       'Social Media Ma0gement', 'Social Media Marketing',
       'Social Media Platforms', 'Social Network Media', 'Social News',
       'Social Recruiting', 'Social Television', 'Social Travel',
       'Software', 'Solar', 'Space Travel', 'Specialty Chemicals',
       'Specialty Foods', 'Speech Recognition', 'Sporting Goods',
       'Sports', 'Staffing Firms', 'Startups', 'Stock Exchanges',
       'Storage', 'Subscription Service', 'Supply Chain Ma0gement',
       'Surveys', 'Synchronization', 'Systems', 'Task Ma0gement', 'Taxis',
       'Tea', 'Technology', 'Telecommunications', 'Television',
       'Textiles', 'Theatre', 'Therapeutics', 'Ticketing', 'Tourism',
       'Tracking', 'Trading', 'Training', 'Translation', 'Transportation',
       'Travel', 'Travel & Tourism', 'Universities',
       'University Students', 'Unmanned Air Systems', 'Usability',
       'User Experience Design', 'User Interface', 'Utilities',
       'Vending and Concessions', 'Venture Capital', 'Veteri0ry', 'Video',
       'Video Conferencing', 'Video Games', 'Video on Demand',
       'Video Streaming', 'Virtual Workforces', 'VoIP', 'Waste Ma0gement',
       'Watch', 'Water', 'Water Purification', 'Wearables',
       'Web Browsers', 'Web Design', 'Web Development', 'Web Hosting',
       'Web Tools', 'Weddings', 'Wholesale', 'Wine And Spirits',
       'Wireless', 'Women', 'Young Adults'], dtype=object)

In [67]:
mapping.sum()

Automotive & Sports                         22
Blanks                                       1
Cleantech / Semiconductors                  53
Entertainment                               89
Health                                      63
Manufacturing                               40
News, Search and Messaging                  72
Others                                     195
Social, Finance, Analytics, Advertising    153
dtype: int64

In [100]:
sector = pd.melt(mapping,id_vars=['category_list'],var_name='main_sector')
sector

         category_list                              main_sector  value
0                  NaN                      Automotive & Sports      0
1                   3D                      Automotive & Sports      0
2          3D Printing                      Automotive & Sports      0
3        3D Technology                      Automotive & Sports      0
4           Accounting                      Automotive & Sports      0
...                ...                                      ...    ...
6187         Wholesale  Social, Finance, Analytics, Advertising      0
6188  Wine And Spirits  Social, Finance, Analytics, Advertising      0
6189          Wireless  Social, Finance, Analytics, Advertising      0
6190             Women  Social, Finance, Analytics, Advertising      0
6191      Young Adults  Social, Finance, Analytics, Advertising      0

[6192 rows x 3 columns]

In [102]:
sector= sector[sector.value==1]
sector

          category_list                              main_sector  value
8      Adventure Travel                      Automotive & Sports      1
14            Aerospace                      Automotive & Sports      1
45                 Auto                      Automotive & Sports      1
46      Automated Kiosk                      Automotive & Sports      1
47           Automotive                      Automotive & Sports      1
...                 ...                                      ...    ...
6121  Social Recruiting  Social, Finance, Analytics, Advertising      1
6122  Social Television  Social, Finance, Analytics, Advertising      1
6123      Social Travel  Social, Finance, Analytics, Advertising      1
6134    Stock Exchanges  Social, Finance, Analytics, Advertising      1
6167    Venture Capital  Social, Finance, Analytics, Advertising      1

[688 rows x 3 columns]

In [103]:
sector = sector.drop('value',axis=1)
sector

          category_list                              main_sector
8      Adventure Travel                      Automotive & Sports
14            Aerospace                      Automotive & Sports
45                 Auto                      Automotive & Sports
46      Automated Kiosk                      Automotive & Sports
47           Automotive                      Automotive & Sports
...                 ...                                      ...
6121  Social Recruiting  Social, Finance, Analytics, Advertising
6122  Social Television  Social, Finance, Analytics, Advertising
6123      Social Travel  Social, Finance, Analytics, Advertising
6134    Stock Exchanges  Social, Finance, Analytics, Advertising
6167    Venture Capital  Social, Finance, Analytics, Advertising

[688 rows x 2 columns]

In [104]:
sector.dtypes

category_list    object
main_sector      object
dtype: object

In [77]:
master_frame.columns

Index(['funding_round_permalink', 'funding_round_type', 'funded_at',
       'raised_amount_usd', 'permalink', 'name', 'category_list', 'status',
       'country_code'],
      dtype='object')

In [79]:
master_frame['category_list'].isnull().sum()

579

In [90]:
master_frame['category_list'].fillna('Missing')

0                                                     Media
2         Application Platforms|Real Time|Social Network...
4                                               Curated Web
6                                                     Games
7                                             Biotechnology
                                ...
114935          Advertising|Mobile|Web Development|Wireless
114936          Advertising|Mobile|Web Development|Wireless
114937          Advertising|Mobile|Web Development|Wireless
114938          Advertising|Mobile|Web Development|Wireless
114940    Consumer Electronics|Internet of Things|Teleco...
Name: category_list, Length: 89108, dtype: object

In [94]:
master_frame['category_list'].apply(lambda x: str(x).split('|')[0])

0                         Media
2         Application Platforms
4                   Curated Web
6                         Games
7                 Biotechnology
                  ...
114935              Advertising
114936              Advertising
114937              Advertising
114938              Advertising
114940     Consumer Electronics
Name: category_list, Length: 89108, dtype: object

In [106]:
sector_anl = pd.merge(master_frame,sector,how='inner',on='category_list')
sector_anl.sample(30)

,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,permalink,name,category_list,status,country_code,main_sector
13559,/funding-round/051ccc0904de7d98bf112164fb1f85e3,venture,28-03-2014,100000.0,/organization/health-enhancement-products,Health Enhancement Products,Health and Wellness,operating,USA,Health
37688,/funding-round/de8516f73f7f74cb2fbd295ef44b7986,angel,01-10-2013,415000.0,/organization/exiles,Exiles,Sports,operating,USA,Automotive & Sports
6874,/funding-round/067f6128aee6ee841347c33cc95954bf,seed,10-12-2010,132338.0,/organization/molport,MolPort,Biotechnology,operating,LVA,Cleantech / Semiconductors
16673,/funding-round/86649425a2457a013de7dafbd65225c2,venture,07-07-2004,15000000.0,/organization/convio,Convio,Software,acquired,USA,Others
39643,/funding-round/ad757b1cfc6c5dc8b6139f8522df969a,venture,25-11-2014,11149993.0,/organization/forward-networks,Forward Networks,Computers,operating,USA,Manufacturing
2254,/funding-round/ca40d817f7873398e24afb2a89454f6e,venture,18-07-2013,9600000.0,/organization/abgenomics,AbGenomics,Biotechnology,operating,USA,Cleantech / Semiconductors
26545,/funding-round/e28b30360fd489c93a5e887bf2d62479,venture,06-08-2008,13000000.0,/organization/nextreme,Nextreme Thermal Solutions,Hardware + Software,operating,USA,Manufacturing
27641,/funding-round/339d1aba01dca47443823bf158b9acd1,venture,11-01-2008,2750000.0,/organization/ecomotors,EcoMotors,Clean Technology,operating,USA,Cleantech / Semiconductors
5720,/funding-round/348271f89c934eba7b6307a9af05b469,debt_financing,22-04-2015,48000000.0,/organization/huya-bioscience-international,HUYA Bioscience International,Biotechnology,operating,USA,Cleantech / Semiconductors
32512,/funding-round/2863c54317adedf212f521ec3d469315,venture,11-01-2006,12000000.0,/organization/siverge-networks,Siverge Networks,Semiconductors,operating,ISR,Cleantech / Semiconductors
38364,/funding-round/0d8eb2829075c0686ec4be6d29815a3c,seed,18-12-2011,160000.0,/organization/lellan,Lellan,Design,operating,USA,Automotive & Sports
23968,/funding-round/e164e095b53832b7422cbf4996e67148,venture,01-03-2005,6000000.0,/organization/spectrasensors,SpectraSensors,Manufacturing,operating,USA,Manufacturing
4273,/funding-round/ec556c4768fce43e8f036d1cb6ad112d,debt_financing,08-12-2011,216658.0,/organization/coferon,Coferon,Biotechnology,operating,USA,Cleantech / Semiconductors
21993,/funding-round/511178e7aa02f01450f9faa3e88b789c,venture,08-11-2010,106800.0,/organization/nukona,Nukona,Enterprise Software,acquired,USA,Others
30724,/funding-round/f6ab2269ec2f9a93b8c51b3707c5d4a0,venture,04-10-2006,16000000.0,/organization/novare-surgical,Novare Surgical,Health Care,closed,USA,Health
7977,/funding-round/ec943cfb2837d749350e132cf1ae921d,venture,12-08-2009,180000.0,/organization/protea-biosciences-group,Protea Biosciences Group,Biotechnology,operating,USA,Cleantech / Semiconductors
17450,/funding-round/3fe025ee3417be7559d65bcf9d0f53eb,angel,01-04-2009,750000.0,/organization/geospiza,Geospiza,Software,acquired,USA,Others
3576,/funding-round/e7c8aafe115b6504f73618ab4404b3d3,venture,27-04-2010,423000.0,/organization/biota-holdings,Biota Holdings,Biotechnology,ipo,AUS,Cleantech / Semiconductors
10936,/funding-round/b0712f3c34432bf1d6c78c47ee55fdee,seed,11-02-2014,30000.0,/organization/perpetuall,Perpetuall,Mobile,operating,ESP,"News, Search and Messaging"
38204,/funding-round/a7e54eb0f47b11f105214897659e54a2,equity_crowdfunding,28-09-2014,1000.0,/organization/creamalicious,Creamalicious,Retail,operating,USA,"Social, Finance, Analytics, Advertising"
33244,/funding-round/f991cc77ac176c76c1291329a8db3530,venture,17-10-2005,12000000.0,/organization/smartsynch,SmartSynch,Web Hosting,acquired,USA,Others
21260,/funding-round/7474685d2fbb92d2e05dc79638c2695a,seed,09-09-2014,1130000.0,/organization/backtrace-i-o,Backtrace,Enterprise Software,operating,USA,Others
1059,/funding-round/d92bb0c3569e3b5dfa4b0741811114f8,venture,11-01-2010,1500001.0,/organization/toptenreviews,TopTenREVIEWS,Curated Web,operating,USA,"News, Search and Messaging"
37078,/funding-round/1a3152b3b9d8f65cff7f253d88b5f099,venture,20-10-2014,455100.0,/organization/nemus-bioscience,NEMUS Bioscience,Pharmaceuticals,ipo,USA,Health
37071,/funding-round/e22c21117b0c06dc71fb565ae9759be2,venture,20-04-2015,16600000.0,/organization/minnesota-medical-solutions,Minnesota Medical Solutions,Pharmaceuticals,operating,USA,Health
20020,/funding-round/d68f63653e13bbdd414cf72df00df77c,seed,31-03-2015,390000.0,/organization/slope,Slope,Software,operating,USA,Others
17535,/funding-round/80cb5390a4eae6261246f4ef769ac8c7,debt_financing,15-04-2013,500000.0,/organization/gridx,GridX,Software,operating,USA,Others
32002,/funding-round/ffa554c99e159d25edc6b703f5afc8c5,venture,04-04-2005,7500000.0,/organization/easic,eASIC,Semiconductors,operating,USA,Cleantech / Semiconductors
17152,/funding-round/10d3c70d6782ee32e9ed67b039a6043c,venture,15-11-2007,5000000.0,/organization/enure-networks,Enure Networks,Software,closed,ISR,Others
18205,/funding-round/2a704e65fe9b478ebeeddee660bc1c2d,venture,11-06-2007,295000.0,/organization/lattice-voice-technologies,Lattice Voice Technologies,Software,operating,GBR,Others